#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 10.15.3

services:
  - docker

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

install:
  - yarn

#运行的脚本命令

script:
  - yarn build

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker build -t irislian199092/test-ci:latest .

  - docker push irislian199092/test-ci:latest
